env:
  browser: true
  es6: true
  jest: true
extends: ['airbnb-base', 'prettier']
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  indent: [2, "tab"],
  "no-tabs": 0,
  semi: 0,
  treatUndefinedAsUnspecified: true,
}
